create extension if not exists pg_net with schema extensions;

create table if not exists tks_products (
  id bigint primary key,
  cat text not null default 'Sem categoria',
  name text not null default 'Sem nome',
  description text not null default '',
  price numeric(10,2) not null default 0,
  image_url text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists tks_orders (
  id bigint primary key,
  created_at timestamptz not null default now(),
  status text not null default 'Recebido',
  customer_name text not null default '',
  customer_phone text not null default '',
  payment text not null default '',
  payment_status text not null default 'pending' check (payment_status in ('pending', 'paid')),
  notes text not null default '',
  subtotal numeric(10,2) not null default 0 check (subtotal >= 0),
  discount_amount numeric(10,2) not null default 0 check (discount_amount >= 0),
  coupon_code text,
  coupon_discount_amount numeric(10,2) not null default 0 check (coupon_discount_amount >= 0),
  surcharge_amount numeric(10,2) not null default 0 check (surcharge_amount >= 0),
  amount_received numeric(10,2) check (amount_received is null or amount_received >= 0),
  change_amount numeric(10,2) not null default 0 check (change_amount >= 0),
  total numeric(10,2) not null default 0,
  items jsonb not null default '[]'::jsonb,
  order_source text not null default 'public',
  client_request_id text,
  archived_at timestamptz
);

create table if not exists tks_promos (
  id bigint generated by default as identity primary key,
  title text not null default '',
  text text not null default '',
  code text,
  discount_type text not null default 'fixed' check (discount_type in ('fixed', 'percent', 'none')),
  discount_value numeric(10,2) not null default 0 check (discount_value >= 0),
  active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

-- Evolução compatível do editor de cardápio: todas as colunas são opcionais para
-- permitir aplicar esta migração em uma instalação que já possui tks_products.
alter table tks_products add column if not exists archived_at timestamptz;
alter table tks_products add column if not exists active_days jsonb not null default '[0,1,2,3,4,5,6]'::jsonb;
alter table tks_products add column if not exists channels jsonb not null default '{"retirada":true,"delivery":false,"mesa":false}'::jsonb;
alter table tks_products add column if not exists badges jsonb not null default '{}'::jsonb;
alter table tks_products add column if not exists highlight boolean not null default false;
alter table tks_products add column if not exists secondary_images jsonb not null default '[]'::jsonb;
alter table tks_products add column if not exists tags jsonb not null default '[]'::jsonb;
alter table tks_products add column if not exists internal_code text not null default '';
alter table tks_products add column if not exists cost numeric(10,2) not null default 0;
alter table tks_products add column if not exists from_price numeric(10,2);
alter table tks_products add column if not exists strike_price numeric(10,2);
alter table tks_products add column if not exists stock_controlled boolean not null default false;
alter table tks_products add column if not exists stock_qty integer;

create unique index if not exists tks_promos_code_unique
  on tks_promos (upper(code))
  where code is not null and btrim(code) <> '';

create table if not exists tks_complements (
  id bigint primary key,
  name text not null default '',
  min_qty integer not null default 0,
  max_qty integer not null default 100,
  active boolean not null default true,
  linked_product_ids jsonb not null default '[]'::jsonb,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists tks_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists tks_cash_sessions (
  id bigint generated by default as identity primary key,
  status text not null default 'open' check (status in ('open', 'closed')),
  opening_amount numeric(12,2) not null default 0 check (opening_amount >= 0),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  counted_amount numeric(12,2),
  expected_amount numeric(12,2),
  difference numeric(12,2),
  opened_by uuid references auth.users(id),
  closed_by uuid references auth.users(id)
);

create table if not exists tks_cash_movements (
  id bigint generated by default as identity primary key,
  session_id bigint not null references tks_cash_sessions(id) on delete restrict,
  type text not null check (type in ('entrada', 'saida')),
  description text not null default '',
  amount numeric(12,2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table if not exists tks_finance_entries (
  id bigint primary key,
  direction text not null default 'payable' check (direction in ('payable', 'receivable')),
  description text not null default '',
  category text not null default '',
  supplier text not null default '',
  due_date date,
  amount numeric(12,2) not null check (amount > 0),
  status text not null default 'open' check (status in ('open', 'paid')),
  recurring boolean not null default false,
  notes text not null default '',
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table if not exists tks_expenses (
  id uuid primary key default gen_random_uuid(),
  expense_date date not null,
  description text not null,
  category text not null default 'Outros',
  supplier text not null default '',
  amount numeric(12,2) not null check (amount > 0),
  notes text not null default '',
  source text not null default 'manual',
  source_record_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  unique (source, source_record_id)
);

create table if not exists tks_finance_daily_revenues (
  id uuid primary key default gen_random_uuid(),
  revenue_date date not null,
  revenue numeric(12,2) not null default 0 check (revenue >= 0),
  orders integer not null default 0 check (orders >= 0),
  source text not null default 'manual',
  source_record_id uuid,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  unique (source, source_record_id),
  unique (revenue_date, source)
);

create table if not exists tks_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists tks_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  expiration_time bigint,
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, endpoint)
);

create table if not exists tks_push_config (
  id boolean primary key default true check (id),
  endpoint_url text not null default '',
  webhook_secret text not null default '',
  updated_at timestamptz not null default now()
);

alter table tks_complements add column if not exists description text not null default '';
alter table tks_complements add column if not exists sort_order integer not null default 0;
alter table tks_complements add column if not exists active_days jsonb not null default '[0,1,2,3,4,5,6]'::jsonb;
alter table tks_complements add column if not exists tags jsonb not null default '[]'::jsonb;

alter table tks_products enable row level security;
alter table tks_orders enable row level security;
alter table tks_promos enable row level security;
alter table tks_complements enable row level security;
alter table tks_settings enable row level security;
alter table tks_admins enable row level security;
alter table tks_cash_sessions enable row level security;
alter table tks_cash_movements enable row level security;
alter table tks_finance_entries enable row level security;
alter table tks_expenses enable row level security;
alter table tks_finance_daily_revenues enable row level security;
alter table tks_push_subscriptions enable row level security;
alter table tks_push_config enable row level security;

create or replace function public.tks_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.tks_admins
    where user_id = auth.uid()
  );
$$;

revoke all on function public.tks_is_admin() from public;
revoke execute on function public.tks_is_admin() from anon;
grant execute on function public.tks_is_admin() to authenticated;

drop policy if exists "public tks products read" on tks_products;
drop policy if exists "public tks products write" on tks_products;
drop policy if exists "public tks orders read" on tks_orders;
drop policy if exists "public tks orders write" on tks_orders;
drop policy if exists "public tks promos read" on tks_promos;
drop policy if exists "public tks promos write" on tks_promos;
drop policy if exists "public tks complements read" on tks_complements;
drop policy if exists "public tks complements write" on tks_complements;
drop policy if exists "public tks settings read" on tks_settings;
drop policy if exists "public tks settings write" on tks_settings;
drop policy if exists "public tks store status read" on tks_settings;
drop policy if exists "public tks store schedule read" on tks_settings;
drop policy if exists "public tks whatsapp contact read" on tks_settings;
drop policy if exists "public tks orders create" on tks_orders;
drop policy if exists "admin tks products all" on tks_products;
drop policy if exists "admin tks orders all" on tks_orders;
drop policy if exists "admin tks promos all" on tks_promos;
drop policy if exists "admin tks complements all" on tks_complements;
drop policy if exists "admin tks settings all" on tks_settings;
drop policy if exists "admin tks cash sessions all" on tks_cash_sessions;
drop policy if exists "admin tks cash movements all" on tks_cash_movements;
drop policy if exists "admin tks finance entries all" on tks_finance_entries;
drop policy if exists "tks expenses admin all" on tks_expenses;
drop policy if exists "tks daily revenues admin all" on tks_finance_daily_revenues;
drop policy if exists "public tokyo products read" on tks_products;
drop policy if exists "public tokyo products write" on tks_products;
drop policy if exists "public tokyo orders read" on tks_orders;
drop policy if exists "public tokyo orders write" on tks_orders;
drop policy if exists "public tokyo promos read" on tks_promos;
drop policy if exists "public tokyo promos write" on tks_promos;
drop policy if exists "public tokyo complements read" on tks_complements;
drop policy if exists "public tokyo complements write" on tks_complements;
drop policy if exists "public tokyo settings read" on tks_settings;
drop policy if exists "public tokyo settings write" on tks_settings;
drop policy if exists "public tokyo store status read" on tks_settings;
drop policy if exists "public tokyo orders create" on tks_orders;
drop policy if exists "admin tokyo products all" on tks_products;
drop policy if exists "admin tokyo orders all" on tks_orders;
drop policy if exists "admin tokyo promos all" on tks_promos;
drop policy if exists "admin tokyo complements all" on tks_complements;
drop policy if exists "admin tokyo settings all" on tks_settings;
drop policy if exists "admin tokyo cash sessions all" on tks_cash_sessions;
drop policy if exists "admin tokyo cash movements all" on tks_cash_movements;
drop policy if exists "admin tokyo finance entries all" on tks_finance_entries;

-- Público: somente leitura do que o cardápio precisa.
-- Admin: usuário autenticado cujo UUID foi registrado em tks_admins.
create policy "public tks products read" on tks_products
  for select to anon using (active = true);

create policy "public tks complements read" on tks_complements
  for select to anon using (active = true);

create policy "public tks settings read" on tks_settings
  for select to anon using (key in ('store_status', 'whatsapp_contact', 'store_schedule'));

create policy "admin tks products all" on tks_products
  for all to authenticated using (public.tks_is_admin()) with check (public.tks_is_admin());

create policy "admin tks orders all" on tks_orders
  for all to authenticated using (public.tks_is_admin()) with check (public.tks_is_admin());

create policy "admin tks promos all" on tks_promos
  for all to authenticated using (public.tks_is_admin()) with check (public.tks_is_admin());

create policy "admin tks complements all" on tks_complements
  for all to authenticated using (public.tks_is_admin()) with check (public.tks_is_admin());

create policy "admin tks settings all" on tks_settings
  for all to authenticated using (public.tks_is_admin()) with check (public.tks_is_admin());

create policy "admin tks cash sessions all" on tks_cash_sessions
  for all to authenticated using (public.tks_is_admin()) with check (public.tks_is_admin());

create policy "admin tks cash movements all" on tks_cash_movements
  for all to authenticated using (public.tks_is_admin()) with check (public.tks_is_admin());

create policy "admin tks finance entries all" on tks_finance_entries
  for all to authenticated using (public.tks_is_admin()) with check (public.tks_is_admin());

create policy "tks expenses admin all" on tks_expenses
  for all to authenticated using (public.tks_is_admin()) with check (public.tks_is_admin());

create policy "tks daily revenues admin all" on tks_finance_daily_revenues
  for all to authenticated using (public.tks_is_admin()) with check (public.tks_is_admin());

create policy "tks push subscriptions own device" on tks_push_subscriptions
  for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

revoke all on tks_admins from public;
revoke all on tks_admins from anon, authenticated;
grant select on tks_products, tks_complements, tks_settings to anon, authenticated;
grant select, insert, update, delete on tks_products, tks_orders, tks_promos, tks_complements, tks_settings to authenticated;
grant usage, select on sequence tks_promos_id_seq to authenticated;
revoke all on tks_cash_sessions, tks_cash_movements from anon, authenticated;
grant select on tks_cash_sessions, tks_cash_movements to authenticated;
revoke all on tks_finance_entries from anon, authenticated;
grant select, insert, update, delete on tks_finance_entries to authenticated;
revoke all on tks_expenses, tks_finance_daily_revenues from anon, authenticated;
grant select, insert, update, delete on tks_expenses, tks_finance_daily_revenues to authenticated;
revoke all on tks_push_config from public, anon, authenticated;
revoke all on tks_push_subscriptions from anon;
grant select, insert, update, delete on tks_push_subscriptions to authenticated;

create or replace function public.tks_get_push_subscriptions(p_secret text)
returns table(endpoint text, p256dh text, auth text)
language sql security definer set search_path = public, pg_temp
as $$
  select subscription.endpoint, subscription.p256dh, subscription.auth
  from public.tks_push_subscriptions subscription
  join public.tks_push_config config on config.id = true
  where config.webhook_secret = p_secret;
$$;

create or replace function public.tks_remove_push_subscription(p_secret text, p_endpoint text)
returns void
language sql security definer set search_path = public, pg_temp
as $$
  delete from public.tks_push_subscriptions subscription
  using public.tks_push_config config
  where config.id = true and config.webhook_secret = p_secret and subscription.endpoint = p_endpoint;
$$;

revoke all on function public.tks_get_push_subscriptions(text) from public, authenticated;
revoke all on function public.tks_remove_push_subscription(text, text) from public, authenticated;
grant execute on function public.tks_get_push_subscriptions(text) to anon;
grant execute on function public.tks_remove_push_subscription(text, text) to anon;

insert into tks_complements (id, name, min_qty, max_qty, active, linked_product_ids, items, tags)
values
  (
    9001,
    'Cream Cheese no Hot',
    0,
    100,
    true,
    '[5141360, 5141386]'::jsonb,
    '[{"id":9101,"name":"Cream Cheese","price":4,"active":true}]'::jsonb,
    '["pdv-global"]'::jsonb
  ),
  (
    9002,
    'Flambado',
    0,
    100,
    true,
    '[5160817]'::jsonb,
    '[{"id":9102,"name":"Flambado","price":2,"active":true}]'::jsonb,
    '["pdv-global"]'::jsonb
  )
on conflict (id) do update set
  name = excluded.name,
  min_qty = excluded.min_qty,
  max_qty = excluded.max_qty,
  active = excluded.active,
  linked_product_ids = excluded.linked_product_ids,
  items = excluded.items,
  tags = excluded.tags;

insert into tks_settings (key, value)
values ('store_status', '{"mode":"open","label":"Aberto para retirada","manualOverride":false}'::jsonb)
on conflict (key) do nothing;

insert into tks_settings (key, value)
values ('store_schedule', '{"enabled":false,"weekly":[]}'::jsonb)
on conflict (key) do nothing;

-- Camada de segurança e integridade da criação pública de pedidos.
-- O navegador envia apenas uma intenção; esta função recalcula preços e adicionais.
alter table tks_orders add column if not exists order_source text not null default 'public';
alter table tks_orders add column if not exists client_request_id text;
alter table tks_orders add column if not exists archived_at timestamptz;
alter table tks_orders add column if not exists payment_status text not null default 'pending';
do $$
begin
  alter table tks_orders add constraint tks_orders_payment_status_check check (payment_status in ('pending', 'paid'));
exception when duplicate_object then null;
end;
$$;

-- A baixa representa a entrega concluída e só pode ocorrer depois da confirmação do pagamento.
create or replace function public.tks_guard_order_finalization()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.status = 'Finalizado' and coalesce(new.payment_status, 'pending') <> 'paid' then
    raise exception using errcode = '22023', message = 'Marque o pedido como pago antes de dar baixa.';
  end if;
  return new;
end;
$$;

revoke all on function public.tks_guard_order_finalization() from public, anon, authenticated;
drop trigger if exists tks_orders_require_paid_finalization on public.tks_orders;
create trigger tks_orders_require_paid_finalization
before update of status on public.tks_orders
for each row execute function public.tks_guard_order_finalization();

create sequence if not exists tks_order_number_seq;

do $$
declare
  next_id bigint;
  current_sequence bigint;
begin
  select coalesce(max(id), 0) + 1 into next_id from public.tks_orders;
  select last_value into current_sequence from public.tks_order_number_seq;
  if current_sequence < next_id then
    perform setval('public.tks_order_number_seq', next_id, false);
  end if;
end;
$$;

alter table tks_orders alter column id set default nextval('public.tks_order_number_seq');
drop index if exists public.tks_orders_client_request_id_idx;
create unique index tks_orders_client_request_id_idx
  on tks_orders (client_request_id);

do $$
declare
  policy_row record;
begin
  for policy_row in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'tks_orders'
  loop
    execute format('drop policy if exists %I on public.tks_orders', policy_row.policyname);
  end loop;
end;
$$;

create or replace function public.tks_store_is_open()
returns boolean
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  schedule jsonb;
  status jsonb;
  today jsonb;
  previous jsonb;
  weekday integer := extract(dow from (now() at time zone 'America/Sao_Paulo'))::integer;
  current_time_value time := (now() at time zone 'America/Sao_Paulo')::time;
  opening time;
  closing time;
begin
  select value into schedule from public.tks_settings where key = 'store_schedule';
  select value into status from public.tks_settings where key = 'store_status';
  if coalesce((status->>'manualOverride')::boolean, (status->>'manual_override')::boolean, false) is true
    or lower(coalesce(status->>'mode', 'open')) in ('paused', 'closed') then
    return lower(coalesce(status->>'mode', 'open')) = 'open';
  end if;
  if coalesce((schedule->>'enabled')::boolean, false) is not true then
    return lower(coalesce(status->>'mode', 'open')) = 'open';
  end if;

  select value into today
  from jsonb_array_elements(coalesce(schedule->'weekly', '[]'::jsonb)) item(value)
  where (value->>'day')::integer = weekday
  limit 1;
  select value into previous
  from jsonb_array_elements(coalesce(schedule->'weekly', '[]'::jsonb)) item(value)
  where (value->>'day')::integer = ((weekday + 6) % 7)
  limit 1;

  if today is not null and coalesce((today->>'enabled')::boolean, false) is true then
    opening := nullif(today->>'open', '')::time;
    closing := nullif(today->>'close', '')::time;
    if opening is not null and closing is not null and opening <> closing then
      if opening < closing then
        return current_time_value >= opening and current_time_value < closing;
      end if;
      if current_time_value >= opening then
        return true;
      end if;
    end if;
  end if;

  if previous is not null and coalesce((previous->>'enabled')::boolean, false) is true then
    opening := nullif(previous->>'open', '')::time;
    closing := nullif(previous->>'close', '')::time;
    if opening is not null and closing is not null and opening > closing and current_time_value < closing then
      return true;
    end if;
  end if;
  return false;
exception when others then
  return false;
end;
$$;

revoke all on function public.tks_store_is_open() from public;
grant execute on function public.tks_store_is_open() to anon, authenticated;

create or replace function public.tks_create_order(p_order jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  is_admin boolean := false;
  customer_name_value text;
  customer_phone_value text;
  payment_value text;
  payment_status_value text := 'pending';
  notes_value text;
  client_request_value text;
  source_value text;
  pricing jsonb := '{}'::jsonb;
  discount_type_value text := 'none';
  surcharge_type_value text := 'none';
  discount_input numeric(10,2) := 0;
  surcharge_input numeric(10,2) := 0;
  manual_discount_amount numeric(10,2) := 0;
  coupon_discount_amount numeric(10,2) := 0;
  surcharge_amount_value numeric(10,2) := 0;
  subtotal_value numeric(10,2) := 0;
  amount_received_value numeric(10,2);
  change_amount_value numeric(10,2) := 0;
  coupon_code_value text;
  coupon_row public.tks_promos%rowtype;
  input_items jsonb;
  item_row record;
  option_row record;
  product_row public.tks_products%rowtype;
  complement_row public.tks_complements%rowtype;
  validation_group record;
  complement_item jsonb;
  item_options jsonb;
  sanitized_items jsonb := '[]'::jsonb;
  product_id bigint;
  group_id bigint;
  option_id bigint;
  item_quantity integer;
  option_quantity integer;
  group_quantity integer;
  base_price numeric(10,2);
  extras_total numeric(10,2);
  line_total numeric(10,2);
  total_value numeric(10,2) := 0;
  existing_order_id bigint;
  created_order_id bigint;
begin
  if p_order is null or jsonb_typeof(p_order) <> 'object' then
    raise exception using errcode = '22023', message = 'Pedido inválido.';
  end if;

  if auth.uid() is not null then
    is_admin := public.tks_is_admin();
  end if;

  if not is_admin and not public.tks_store_is_open() then
    raise exception using errcode = 'P0001', message = 'O cardápio está fechado para novos pedidos.';
  end if;

  customer_name_value := trim(coalesce(p_order->>'customer_name', ''));
  customer_phone_value := regexp_replace(coalesce(p_order->>'customer_phone', ''), '[^0-9]', '', 'g');
  payment_value := trim(coalesce(p_order->>'payment', ''));
  payment_status_value := case when is_admin and lower(coalesce(p_order->>'payment_status', 'pending')) = 'paid' then 'paid' else 'pending' end;
  notes_value := trim(coalesce(p_order->>'notes', ''));
  client_request_value := nullif(trim(coalesce(p_order->>'client_request_id', '')), '');
  source_value := case when is_admin then coalesce(nullif(trim(p_order->>'order_source'), ''), 'pdv') else 'public' end;
  -- O público pode informar apenas o dinheiro recebido. Descontos, acréscimos
  -- e cupons continuam exclusivos do PDV autenticado.
  pricing := case
    when is_admin then coalesce(p_order->'pricing', '{}'::jsonb)
    else jsonb_build_object('amount_received', coalesce(p_order->'pricing'->>'amount_received', ''))
  end;
  input_items := coalesce(p_order->'items', '[]'::jsonb);

  if char_length(customer_name_value) not between 2 and 120 then
    raise exception using errcode = '22023', message = 'Nome do cliente inválido.';
  end if;
  if char_length(customer_phone_value) not between 10 and 15 then
    raise exception using errcode = '22023', message = 'Celular do cliente inválido.';
  end if;
  if char_length(notes_value) > 1000 then
    raise exception using errcode = '22023', message = 'Observação muito longa.';
  end if;
  if jsonb_typeof(input_items) <> 'array' or jsonb_array_length(input_items) not between 1 and 50 then
    raise exception using errcode = '22023', message = 'O pedido precisa ter entre 1 e 50 itens.';
  end if;

  if client_request_value is not null then
    select id into existing_order_id
    from public.tks_orders
    where client_request_id = client_request_value
    limit 1;
    if existing_order_id is not null then
      return jsonb_build_object('id', existing_order_id, 'deduplicated', true);
    end if;
  end if;

  for item_row in select value from jsonb_array_elements(input_items) as item(value) loop
    begin
      product_id := (item_row.value->>'id')::bigint;
      item_quantity := (item_row.value->>'qty')::integer;
    exception when invalid_text_representation then
      raise exception using errcode = '22023', message = 'Produto ou quantidade inválida.';
    end;

    if item_quantity not between 1 and 50 then
      raise exception using errcode = '22023', message = 'Quantidade de produto inválida.';
    end if;

    select * into product_row
    from public.tks_products
    where id = product_id and active = true;
    if not found then
      raise exception using errcode = '22023', message = 'Produto indisponível.';
    end if;

    base_price := round(coalesce(product_row.price, 0), 2);
    extras_total := 0;
    item_options := '[]'::jsonb;

    for option_row in select value from jsonb_array_elements(coalesce(item_row.value->'options', '[]'::jsonb)) as option(value) loop
      begin
        group_id := (option_row.value->>'groupId')::bigint;
        option_id := (option_row.value->>'itemId')::bigint;
        option_quantity := (option_row.value->>'qty')::integer;
      exception when invalid_text_representation then
        raise exception using errcode = '22023', message = 'Adicional inválido.';
      end;

      if option_quantity not between 1 and 50 then
        raise exception using errcode = '22023', message = 'Quantidade de adicional inválida.';
      end if;

      select * into complement_row
      from public.tks_complements candidate_group
      where candidate_group.id = group_id
        and candidate_group.active = true
        and (
          exists (
            select 1 from jsonb_array_elements_text(coalesce(candidate_group.linked_product_ids, '[]'::jsonb)) linked(linked_product_id)
            where linked.linked_product_id = product_id::text
          )
          or (
            is_admin
            and lower(trim(coalesce(product_row.cat, ''))) not in ('bebidas', 'combos')
            and 'pdv-global' in (
              select jsonb_array_elements_text(coalesce(candidate_group.tags, '[]'::jsonb))
            )
          )
        );
      if not found then
        raise exception using errcode = '22023', message = 'Grupo de adicional inválido.';
      end if;

      select value into complement_item
      from jsonb_array_elements(coalesce(complement_row.items, '[]'::jsonb)) item(value)
      where (value->>'id')::bigint = option_id
        and coalesce((value->>'active')::boolean, true) = true
      limit 1;
      if complement_item is null then
        raise exception using errcode = '22023', message = 'Adicional indisponível.';
      end if;

      extras_total := extras_total + round(coalesce((complement_item->>'price')::numeric, 0), 2) * option_quantity;
      item_options := item_options || jsonb_build_array(jsonb_build_object(
        'groupId', group_id,
        'groupName', complement_row.name,
        'itemId', option_id,
        'name', complement_item->>'name',
        'price', round(coalesce((complement_item->>'price')::numeric, 0), 2),
        'qty', option_quantity
      ));
    end loop;

    for validation_group in
      select candidate_group.id, candidate_group.min_qty, candidate_group.max_qty
      from public.tks_complements candidate_group
      where candidate_group.active = true
        and (
          exists (
            select 1 from jsonb_array_elements_text(coalesce(candidate_group.linked_product_ids, '[]'::jsonb)) linked(linked_product_id)
            where linked.linked_product_id = product_id::text
          )
          or (
            is_admin
            and lower(trim(coalesce(product_row.cat, ''))) not in ('bebidas', 'combos')
            and 'pdv-global' in (
              select jsonb_array_elements_text(coalesce(candidate_group.tags, '[]'::jsonb))
            )
          )
        )
    loop
      select coalesce(sum((value->>'qty')::integer), 0) into group_quantity
      from jsonb_array_elements(item_options) selected(value)
      where (value->>'groupId')::bigint = validation_group.id;
      if group_quantity < coalesce(validation_group.min_qty, 0) or group_quantity > coalesce(validation_group.max_qty, 100) then
        raise exception using errcode = '22023', message = 'Quantidade de adicionais inválida.';
      end if;
    end loop;

    line_total := round((base_price + extras_total) * item_quantity, 2);
    total_value := total_value + line_total;
    sanitized_items := sanitized_items || jsonb_build_array(jsonb_build_object(
      'id', product_row.id,
      'name', product_row.name,
      'price', round(base_price + extras_total, 2),
      'basePrice', base_price,
      'qty', item_quantity,
      'options', item_options
    ));
  end loop;

  subtotal_value := round(total_value, 2);
  discount_type_value := lower(coalesce(nullif(trim(pricing->>'discount_type'), ''), 'none'));
  surcharge_type_value := lower(coalesce(nullif(trim(pricing->>'surcharge_type'), ''), 'none'));
  discount_input := coalesce(nullif(pricing->>'discount_value', ''), '0')::numeric;
  surcharge_input := coalesce(nullif(pricing->>'surcharge_value', ''), '0')::numeric;
  coupon_code_value := nullif(upper(trim(coalesce(pricing->>'coupon_code', ''))), '');
  amount_received_value := nullif(pricing->>'amount_received', '')::numeric;

  if discount_type_value not in ('none', 'fixed', 'percent') or surcharge_type_value not in ('none', 'fixed', 'percent') then
    raise exception using errcode = '22023', message = 'Tipo de ajuste inválido.';
  end if;
  if discount_input < 0 or surcharge_input < 0 then
    raise exception using errcode = '22023', message = 'Valor de ajuste inválido.';
  end if;
  if discount_type_value = 'percent' and discount_input > 100 then
    raise exception using errcode = '22023', message = 'Desconto percentual não pode passar de 100%.';
  end if;
  if surcharge_type_value = 'percent' and surcharge_input > 100 then
    raise exception using errcode = '22023', message = 'Acréscimo percentual não pode passar de 100%.';
  end if;

  manual_discount_amount := case
    when discount_type_value = 'percent' then round(subtotal_value * discount_input / 100, 2)
    when discount_type_value = 'fixed' then least(discount_input, subtotal_value)
    else 0
  end;

  if coupon_code_value is not null then
    select * into coupon_row
    from public.tks_promos
    where upper(code) = coupon_code_value
      and active = true
      and (starts_at is null or starts_at <= now())
      and (ends_at is null or ends_at >= now())
    limit 1;
    if not found or coupon_row.discount_type = 'none' or coupon_row.discount_value <= 0 then
      raise exception using errcode = '22023', message = 'Cupom inválido, inativo ou expirado.';
    end if;
    coupon_discount_amount := case
      when coupon_row.discount_type = 'percent' then round(greatest(subtotal_value - manual_discount_amount, 0) * least(coupon_row.discount_value, 100) / 100, 2)
      else least(coupon_row.discount_value, greatest(subtotal_value - manual_discount_amount, 0))
    end;
  end if;

  surcharge_amount_value := case
    when surcharge_type_value = 'percent' then round(greatest(subtotal_value - manual_discount_amount - coupon_discount_amount, 0) * surcharge_input / 100, 2)
    when surcharge_type_value = 'fixed' then surcharge_input
    else 0
  end;
  total_value := round(greatest(subtotal_value - manual_discount_amount - coupon_discount_amount, 0) + surcharge_amount_value, 2);
  if lower(payment_value) = 'dinheiro' then
    if amount_received_value is null or amount_received_value < total_value then
      raise exception using errcode = '22023', message = 'O valor recebido é menor que o total do pedido.';
    end if;
    change_amount_value := round(amount_received_value - total_value, 2);
  else
    amount_received_value := null;
    change_amount_value := 0;
  end if;

  insert into public.tks_orders (
    status, customer_name, customer_phone, payment, payment_status, notes, subtotal, discount_amount,
    coupon_code, coupon_discount_amount, surcharge_amount, amount_received, change_amount,
    total, items,
    order_source, client_request_id
  ) values (
    'Recebido', customer_name_value, customer_phone_value, payment_value, payment_status_value, notes_value,
    subtotal_value, manual_discount_amount, coupon_code_value, coupon_discount_amount,
    surcharge_amount_value, amount_received_value, change_amount_value,
    total_value, sanitized_items, source_value, client_request_value
  )
  on conflict (client_request_id) do nothing
  returning id into created_order_id;

  if created_order_id is null and client_request_value is not null then
    select id into created_order_id
    from public.tks_orders
    where client_request_id = client_request_value
    limit 1;
  end if;

  return jsonb_build_object(
    'id', created_order_id,
    'total', round(total_value, 2),
    'items', sanitized_items,
    'deduplicated', false
  );
end;
$$;

revoke all on function public.tks_create_order(jsonb) from public;
grant execute on function public.tks_create_order(jsonb) to anon, authenticated;

revoke all on public.tks_orders from anon;
revoke insert on public.tks_orders from authenticated;
grant select, update, delete on public.tks_orders to authenticated;

create policy "admin tks orders all" on public.tks_orders
  for all to authenticated
  using (public.tks_is_admin())
  with check (public.tks_is_admin());

create or replace function public.tks_open_cash_session(p_opening_amount numeric)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  session_row public.tks_cash_sessions%rowtype;
begin
  if not public.tks_is_admin() then
    raise exception using errcode = '42501', message = 'Acesso negado.';
  end if;
  if p_opening_amount is null or p_opening_amount < 0 then
    raise exception using errcode = '22023', message = 'Valor de abertura inválido.';
  end if;
  if exists (select 1 from public.tks_cash_sessions where status = 'open') then
    raise exception using errcode = 'P0001', message = 'Já existe um caixa aberto.';
  end if;

  insert into public.tks_cash_sessions (opening_amount, opened_by)
  values (round(p_opening_amount, 2), auth.uid())
  returning * into session_row;

  return jsonb_build_object(
    'id', session_row.id,
    'open', true,
    'opening', session_row.opening_amount,
    'openedAt', session_row.opened_at,
    'transactions', '[]'::jsonb
  );
end;
$$;

create or replace function public.tks_record_cash_movement(
  p_session_id bigint,
  p_type text,
  p_amount numeric,
  p_description text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  movement_row public.tks_cash_movements%rowtype;
begin
  if not public.tks_is_admin() then
    raise exception using errcode = '42501', message = 'Acesso negado.';
  end if;
  if p_type not in ('entrada', 'saida') or p_amount is null or p_amount <= 0 then
    raise exception using errcode = '22023', message = 'Movimento de caixa inválido.';
  end if;
  if not exists (select 1 from public.tks_cash_sessions where id = p_session_id and status = 'open') then
    raise exception using errcode = 'P0001', message = 'Caixa fechado ou inexistente.';
  end if;

  insert into public.tks_cash_movements (session_id, type, amount, description, created_by)
  values (p_session_id, p_type, round(p_amount, 2), left(trim(coalesce(p_description, '')), 240), auth.uid())
  returning * into movement_row;

  return jsonb_build_object(
    'id', movement_row.id,
    'type', movement_row.type,
    'value', movement_row.amount,
    'description', movement_row.description,
    'createdAt', movement_row.created_at
  );
end;
$$;

create or replace function public.tks_close_cash_session(p_session_id bigint, p_counted_amount numeric)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  session_row public.tks_cash_sessions%rowtype;
  movements_in numeric(12,2);
  movements_out numeric(12,2);
  sales_total numeric(12,2);
  expected_total numeric(12,2);
begin
  if not public.tks_is_admin() then
    raise exception using errcode = '42501', message = 'Acesso negado.';
  end if;
  if p_counted_amount is null or p_counted_amount < 0 then
    raise exception using errcode = '22023', message = 'Valor contado inválido.';
  end if;

  select * into session_row
  from public.tks_cash_sessions
  where id = p_session_id and status = 'open'
  for update;
  if not found then
    raise exception using errcode = 'P0001', message = 'Caixa fechado ou inexistente.';
  end if;

  select coalesce(sum(amount) filter (where type = 'entrada'), 0),
         coalesce(sum(amount) filter (where type = 'saida'), 0)
  into movements_in, movements_out
  from public.tks_cash_movements
  where session_id = p_session_id;

  select coalesce(sum(total), 0) into sales_total
  from public.tks_orders
  where created_at >= session_row.opened_at
    and created_at <= now()
    and status <> 'Cancelado'
    and archived_at is null;

  expected_total := round(session_row.opening_amount + sales_total + movements_in - movements_out, 2);

  update public.tks_cash_sessions
  set status = 'closed',
      closed_at = now(),
      counted_amount = round(p_counted_amount, 2),
      expected_amount = expected_total,
      difference = round(p_counted_amount - expected_total, 2),
      closed_by = auth.uid()
  where id = p_session_id
  returning * into session_row;

  return jsonb_build_object(
    'id', session_row.id,
    'open', false,
    'opening', session_row.opening_amount,
    'openedAt', session_row.opened_at,
    'closedAt', session_row.closed_at,
    'countedAmount', session_row.counted_amount,
    'expectedAmount', session_row.expected_amount,
    'difference', session_row.difference,
    'transactions', '[]'::jsonb
  );
end;
$$;

revoke all on function public.tks_open_cash_session(numeric) from public;
revoke all on function public.tks_record_cash_movement(bigint, text, numeric, text) from public;
revoke all on function public.tks_close_cash_session(bigint, numeric) from public;
revoke execute on function public.tks_open_cash_session(numeric) from anon;
revoke execute on function public.tks_record_cash_movement(bigint, text, numeric, text) from anon;
revoke execute on function public.tks_close_cash_session(bigint, numeric) from anon;
grant execute on function public.tks_open_cash_session(numeric) to authenticated;
grant execute on function public.tks_record_cash_movement(bigint, text, numeric, text) to authenticated;
grant execute on function public.tks_close_cash_session(bigint, numeric) to authenticated;

create or replace function public.tks_set_push_subscription_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists tks_push_subscriptions_updated_at on public.tks_push_subscriptions;
create trigger tks_push_subscriptions_updated_at
before update on public.tks_push_subscriptions
for each row execute function public.tks_set_push_subscription_updated_at();

create or replace function public.tks_queue_new_order_push()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  push_config public.tks_push_config%rowtype;
begin
  select * into push_config from public.tks_push_config where id = true;
  if coalesce(push_config.endpoint_url, '') = '' or coalesce(push_config.webhook_secret, '') = '' then
    return new;
  end if;
  perform net.http_post(
    url := push_config.endpoint_url,
    headers := jsonb_build_object('Content-Type', 'application/json', 'X-TKS-Webhook-Secret', push_config.webhook_secret),
    body := jsonb_build_object('order', jsonb_build_object('id', new.id, 'customer_name', new.customer_name, 'total', new.total, 'created_at', new.created_at))
  );
  return new;
exception when others then
  raise warning 'Falha ao enfileirar Push do pedido %: %', new.id, sqlerrm;
  return new;
end;
$$;

revoke all on function public.tks_set_push_subscription_updated_at() from public, anon, authenticated;
revoke all on function public.tks_queue_new_order_push() from public, anon, authenticated;
drop trigger if exists tks_orders_push_after_insert on public.tks_orders;
create trigger tks_orders_push_after_insert
after insert on public.tks_orders
for each row execute function public.tks_queue_new_order_push();

create index if not exists tks_cash_movements_created_by_idx on public.tks_cash_movements (created_by);
create index if not exists tks_cash_movements_session_id_idx on public.tks_cash_movements (session_id);
create index if not exists tks_cash_sessions_closed_by_idx on public.tks_cash_sessions (closed_by);
create index if not exists tks_cash_sessions_opened_by_idx on public.tks_cash_sessions (opened_by);
create index if not exists tks_expenses_created_by_idx on public.tks_expenses (created_by);
create index if not exists tks_finance_daily_revenues_created_by_idx on public.tks_finance_daily_revenues (created_by);
create index if not exists tks_finance_entries_created_by_idx on public.tks_finance_entries (created_by);

-- RPC incremental de edição segura de pedido; a migração versionada é a fonte de execução.
create or replace function public.tks_update_order(p_order_id bigint, p_order jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  existing_order public.tks_orders%rowtype;
  updated_order public.tks_orders%rowtype;
  customer_name_value text;
  customer_phone_value text;
  payment_value text;
  notes_value text;
  pricing jsonb := '{}'::jsonb;
  discount_type_value text := 'none';
  surcharge_type_value text := 'none';
  discount_input numeric(10,2) := 0;
  surcharge_input numeric(10,2) := 0;
  input_items jsonb;
  item_row record;
  option_row record;
  product_row public.tks_products%rowtype;
  complement_row public.tks_complements%rowtype;
  validation_group record;
  complement_item jsonb;
  item_options jsonb;
  sanitized_items jsonb := '[]'::jsonb;
  product_id bigint;
  group_id bigint;
  option_id bigint;
  item_quantity integer;
  option_quantity integer;
  group_quantity integer;
  base_price numeric(10,2);
  extras_total numeric(10,2);
  line_total numeric(10,2);
  subtotal_value numeric(10,2) := 0;
  discount_amount_value numeric(10,2) := 0;
  coupon_discount_amount_value numeric(10,2) := 0;
  surcharge_amount_value numeric(10,2) := 0;
  amount_received_value numeric(10,2);
  change_amount_value numeric(10,2) := 0;
  total_value numeric(10,2) := 0;
begin
  if not public.tks_is_admin() then
    raise exception using errcode = '42501', message = 'Acesso negado.';
  end if;
  if p_order is null or jsonb_typeof(p_order) <> 'object' then
    raise exception using errcode = '22023', message = 'Pedido inválido.';
  end if;

  select * into existing_order
  from public.tks_orders
  where id = p_order_id
  for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'Pedido não encontrado.';
  end if;
  if existing_order.archived_at is not null or existing_order.status in ('Finalizado', 'Cancelado') then
    raise exception using errcode = '22023', message = 'Pedidos finalizados ou cancelados não podem ser editados.';
  end if;

  customer_name_value := trim(coalesce(p_order->>'customer_name', existing_order.customer_name));
  customer_phone_value := regexp_replace(coalesce(p_order->>'customer_phone', existing_order.customer_phone), '[^0-9]', '', 'g');
  payment_value := trim(coalesce(nullif(p_order->>'payment', ''), existing_order.payment));
  notes_value := trim(coalesce(p_order->>'notes', existing_order.notes));
  input_items := coalesce(p_order->'items', '[]'::jsonb);
  pricing := coalesce(p_order->'pricing', '{}'::jsonb);

  if char_length(customer_name_value) not between 2 and 120 then
    raise exception using errcode = '22023', message = 'Nome do cliente inválido.';
  end if;
  if char_length(customer_phone_value) not between 10 and 15 then
    raise exception using errcode = '22023', message = 'Celular do cliente inválido.';
  end if;
  if char_length(notes_value) > 1000 then
    raise exception using errcode = '22023', message = 'Observação muito longa.';
  end if;
  if jsonb_typeof(input_items) <> 'array' or jsonb_array_length(input_items) not between 1 and 50 then
    raise exception using errcode = '22023', message = 'O pedido precisa ter entre 1 e 50 itens.';
  end if;

  for item_row in select value from jsonb_array_elements(input_items) as item(value) loop
    begin
      product_id := (item_row.value->>'id')::bigint;
      item_quantity := (item_row.value->>'qty')::integer;
    exception when invalid_text_representation then
      raise exception using errcode = '22023', message = 'Produto ou quantidade inválida.';
    end;
    if item_quantity not between 1 and 50 then
      raise exception using errcode = '22023', message = 'Quantidade de produto inválida.';
    end if;
    if jsonb_typeof(coalesce(item_row.value->'options', '[]'::jsonb)) <> 'array' then
      raise exception using errcode = '22023', message = 'Adicionais inválidos.';
    end if;

    select * into product_row
    from public.tks_products candidate_product
    where candidate_product.id = product_id
      and (candidate_product.active = true or exists (
        select 1 from jsonb_array_elements(coalesce(existing_order.items, '[]'::jsonb)) old_item(value)
        where (old_item.value->>'id')::bigint = product_id
      ));
    if not found then
      raise exception using errcode = '22023', message = 'Produto indisponível.';
    end if;

    base_price := round(coalesce(product_row.price, 0), 2);
    extras_total := 0;
    item_options := '[]'::jsonb;
    for option_row in select value from jsonb_array_elements(coalesce(item_row.value->'options', '[]'::jsonb)) as option(value) loop
      begin
        group_id := (option_row.value->>'groupId')::bigint;
        option_id := (option_row.value->>'itemId')::bigint;
        option_quantity := (option_row.value->>'qty')::integer;
      exception when invalid_text_representation then
        raise exception using errcode = '22023', message = 'Adicional inválido.';
      end;
      if option_quantity not between 1 and 50 then
        raise exception using errcode = '22023', message = 'Quantidade de adicional inválida.';
      end if;

      select * into complement_row
      from public.tks_complements candidate_group
      where candidate_group.id = group_id
        and candidate_group.active = true
        and (
          exists (
            select 1 from jsonb_array_elements_text(coalesce(candidate_group.linked_product_ids, '[]'::jsonb)) linked(linked_product_id)
            where linked.linked_product_id = product_id::text
          )
          or (
            lower(trim(coalesce(product_row.cat, ''))) not in ('bebidas', 'combos')
            and 'pdv-global' in (select jsonb_array_elements_text(coalesce(candidate_group.tags, '[]'::jsonb)))
          )
        );
      if not found then
        raise exception using errcode = '22023', message = 'Grupo de adicional inválido.';
      end if;

      select value into complement_item
      from jsonb_array_elements(coalesce(complement_row.items, '[]'::jsonb)) item(value)
      where (value->>'id')::bigint = option_id
        and coalesce((value->>'active')::boolean, true) = true
      limit 1;
      if complement_item is null then
        raise exception using errcode = '22023', message = 'Adicional indisponível.';
      end if;

      extras_total := extras_total + round(coalesce((complement_item->>'price')::numeric, 0), 2) * option_quantity;
      item_options := item_options || jsonb_build_array(jsonb_build_object(
        'groupId', group_id,
        'groupName', complement_row.name,
        'itemId', option_id,
        'name', complement_item->>'name',
        'price', round(coalesce((complement_item->>'price')::numeric, 0), 2),
        'qty', option_quantity
      ));
    end loop;

    for validation_group in
      select candidate_group.id, candidate_group.min_qty, candidate_group.max_qty
      from public.tks_complements candidate_group
      where candidate_group.active = true
        and (
          exists (
            select 1 from jsonb_array_elements_text(coalesce(candidate_group.linked_product_ids, '[]'::jsonb)) linked(linked_product_id)
            where linked.linked_product_id = product_id::text
          )
          or (
            lower(trim(coalesce(product_row.cat, ''))) not in ('bebidas', 'combos')
            and 'pdv-global' in (select jsonb_array_elements_text(coalesce(candidate_group.tags, '[]'::jsonb)))
          )
        )
    loop
      select coalesce(sum((value->>'qty')::integer), 0) into group_quantity
      from jsonb_array_elements(item_options) selected(value)
      where (value->>'groupId')::bigint = validation_group.id;
      if group_quantity < coalesce(validation_group.min_qty, 0) or group_quantity > coalesce(validation_group.max_qty, 100) then
        raise exception using errcode = '22023', message = 'Quantidade de adicionais inválida.';
      end if;
    end loop;

    line_total := round((base_price + extras_total) * item_quantity, 2);
    subtotal_value := subtotal_value + line_total;
    sanitized_items := sanitized_items || jsonb_build_array(jsonb_build_object(
      'id', product_row.id,
      'name', product_row.name,
      'price', round(base_price + extras_total, 2),
      'basePrice', base_price,
      'qty', item_quantity,
      'options', item_options
    ));
  end loop;

  subtotal_value := round(subtotal_value, 2);
  discount_type_value := lower(coalesce(nullif(trim(pricing->>'discount_type'), ''), 'none'));
  surcharge_type_value := lower(coalesce(nullif(trim(pricing->>'surcharge_type'), ''), 'none'));
  discount_input := greatest(coalesce(nullif(pricing->>'discount_value', '')::numeric, 0), 0);
  surcharge_input := greatest(coalesce(nullif(pricing->>'surcharge_value', '')::numeric, 0), 0);
  if discount_type_value not in ('none', 'fixed', 'percent') or surcharge_type_value not in ('none', 'fixed', 'percent') then
    raise exception using errcode = '22023', message = 'Tipo de ajuste inválido.';
  end if;
  if discount_type_value = 'percent' and discount_input > 100 then
    raise exception using errcode = '22023', message = 'O desconto percentual não pode passar de 100%.';
  end if;
  if surcharge_type_value = 'percent' and surcharge_input > 100 then
    raise exception using errcode = '22023', message = 'O acréscimo percentual não pode passar de 100%.';
  end if;
  discount_amount_value := case
    when discount_type_value = 'percent' then round(subtotal_value * discount_input / 100, 2)
    when discount_type_value = 'fixed' then least(discount_input, subtotal_value)
    else 0
  end;
  coupon_discount_amount_value := least(greatest(coalesce(existing_order.coupon_discount_amount, 0), 0), greatest(subtotal_value - discount_amount_value, 0));
  surcharge_amount_value := case
    when surcharge_type_value = 'percent' then round(greatest(subtotal_value - discount_amount_value - coupon_discount_amount_value, 0) * surcharge_input / 100, 2)
    when surcharge_type_value = 'fixed' then surcharge_input
    else 0
  end;
  total_value := round(greatest(subtotal_value - discount_amount_value - coupon_discount_amount_value, 0) + surcharge_amount_value, 2);
  amount_received_value := existing_order.amount_received;
  if lower(payment_value) = 'dinheiro' then
    if amount_received_value is null or amount_received_value < total_value then
      raise exception using errcode = '22023', message = 'O valor recebido precisa ser revisado para o novo total.';
    end if;
    change_amount_value := round(amount_received_value - total_value, 2);
  else
    amount_received_value := null;
    change_amount_value := 0;
  end if;

  update public.tks_orders
  set customer_name = customer_name_value,
      customer_phone = customer_phone_value,
      payment = payment_value,
      notes = notes_value,
      subtotal = subtotal_value,
      discount_amount = discount_amount_value,
      coupon_discount_amount = coupon_discount_amount_value,
      surcharge_amount = surcharge_amount_value,
      amount_received = amount_received_value,
      change_amount = change_amount_value,
      total = total_value,
      items = sanitized_items
  where id = p_order_id
  returning * into updated_order;

  return jsonb_build_object(
    'id', updated_order.id,
    'created_at', updated_order.created_at,
    'status', updated_order.status,
    'customer_name', updated_order.customer_name,
    'customer_phone', updated_order.customer_phone,
    'payment', updated_order.payment,
    'payment_status', updated_order.payment_status,
    'notes', updated_order.notes,
    'subtotal', updated_order.subtotal,
    'discount_amount', updated_order.discount_amount,
    'coupon_code', updated_order.coupon_code,
    'coupon_discount_amount', updated_order.coupon_discount_amount,
    'surcharge_amount', updated_order.surcharge_amount,
    'amount_received', updated_order.amount_received,
    'change_amount', updated_order.change_amount,
    'total', updated_order.total,
    'items', updated_order.items,
    'order_source', updated_order.order_source,
    'client_request_id', updated_order.client_request_id,
    'archived_at', updated_order.archived_at
  );
end;
$$;

revoke all on function public.tks_update_order(bigint, jsonb) from public, anon;
grant execute on function public.tks_update_order(bigint, jsonb) to authenticated;
