create table if not exists tokyo_products (
  id bigint primary key,
  cat text not null default 'Sem categoria',
  name text not null default 'Sem nome',
  description text not null default '',
  price numeric(10,2) not null default 0,
  image_url text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists tokyo_orders (
  id bigint primary key,
  created_at timestamptz not null default now(),
  status text not null default 'Recebido',
  customer_name text not null default '',
  customer_phone text not null default '',
  payment text not null default '',
  notes text not null default '',
  total numeric(10,2) not null default 0,
  items jsonb not null default '[]'::jsonb
);

create table if not exists tokyo_promos (
  id bigint generated by default as identity primary key,
  title text not null default '',
  text text not null default '',
  created_at timestamptz not null default now()
);

alter table tokyo_products enable row level security;
alter table tokyo_orders enable row level security;
alter table tokyo_promos enable row level security;

drop policy if exists "public tokyo products read" on tokyo_products;
drop policy if exists "public tokyo products write" on tokyo_products;
drop policy if exists "public tokyo orders read" on tokyo_orders;
drop policy if exists "public tokyo orders write" on tokyo_orders;
drop policy if exists "public tokyo promos read" on tokyo_promos;
drop policy if exists "public tokyo promos write" on tokyo_promos;

-- Politicas abertas para TESTE do MVP.
-- Antes de uso oficial, troque por login/admin protegido.
create policy "public tokyo products read" on tokyo_products for select using (true);
create policy "public tokyo products write" on tokyo_products for all using (true) with check (true);

create policy "public tokyo orders read" on tokyo_orders for select using (true);
create policy "public tokyo orders write" on tokyo_orders for all using (true) with check (true);

create policy "public tokyo promos read" on tokyo_promos for select using (true);
create policy "public tokyo promos write" on tokyo_promos for all using (true) with check (true);
