create table if not exists tokyo_products (
  id bigint primary key,
  cat text not null default 'Sem categoria',
  name text not null default 'Sem nome',
  description text not null default '',
  price numeric(10,2) not null default 0,
  image_url text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists tokyo_orders (
  id bigint primary key,
  created_at timestamptz not null default now(),
  status text not null default 'Recebido',
  customer_name text not null default '',
  customer_phone text not null default '',
  payment text not null default '',
  notes text not null default '',
  total numeric(10,2) not null default 0,
  items jsonb not null default '[]'::jsonb
);

create table if not exists tokyo_promos (
  id bigint generated by default as identity primary key,
  title text not null default '',
  text text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists tokyo_complements (
  id bigint primary key,
  name text not null default '',
  min_qty integer not null default 0,
  max_qty integer not null default 100,
  active boolean not null default true,
  linked_product_ids jsonb not null default '[]'::jsonb,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists tokyo_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table tokyo_products enable row level security;
alter table tokyo_orders enable row level security;
alter table tokyo_promos enable row level security;
alter table tokyo_complements enable row level security;
alter table tokyo_settings enable row level security;

drop policy if exists "public tokyo products read" on tokyo_products;
drop policy if exists "public tokyo products write" on tokyo_products;
drop policy if exists "public tokyo orders read" on tokyo_orders;
drop policy if exists "public tokyo orders write" on tokyo_orders;
drop policy if exists "public tokyo promos read" on tokyo_promos;
drop policy if exists "public tokyo promos write" on tokyo_promos;
drop policy if exists "public tokyo complements read" on tokyo_complements;
drop policy if exists "public tokyo complements write" on tokyo_complements;
drop policy if exists "public tokyo settings read" on tokyo_settings;
drop policy if exists "public tokyo settings write" on tokyo_settings;

-- Politicas abertas para TESTE do MVP.
-- Antes de uso oficial, troque por login/admin protegido.
create policy "public tokyo products read" on tokyo_products for select using (true);
create policy "public tokyo products write" on tokyo_products for all using (true) with check (true);

create policy "public tokyo orders read" on tokyo_orders for select using (true);
create policy "public tokyo orders write" on tokyo_orders for all using (true) with check (true);

create policy "public tokyo promos read" on tokyo_promos for select using (true);
create policy "public tokyo promos write" on tokyo_promos for all using (true) with check (true);

create policy "public tokyo complements read" on tokyo_complements for select using (true);
create policy "public tokyo complements write" on tokyo_complements for all using (true) with check (true);

create policy "public tokyo settings read" on tokyo_settings for select using (true);
create policy "public tokyo settings write" on tokyo_settings for all using (true) with check (true);

insert into tokyo_complements (id, name, min_qty, max_qty, active, linked_product_ids, items)
values
  (
    9001,
    'Cream Cheese no Hot',
    0,
    100,
    true,
    '[5141360, 5141386]'::jsonb,
    '[{"id":9101,"name":"Cream Cheese","price":4,"active":true}]'::jsonb
  ),
  (
    9002,
    'Flambado',
    0,
    100,
    true,
    '[5160817]'::jsonb,
    '[{"id":9102,"name":"Flambado","price":2,"active":true}]'::jsonb
  )
on conflict (id) do update set
  name = excluded.name,
  min_qty = excluded.min_qty,
  max_qty = excluded.max_qty,
  active = excluded.active,
  linked_product_ids = excluded.linked_product_ids,
  items = excluded.items;

insert into tokyo_settings (key, value)
values ('store_status', '{"mode":"open","label":"Aberto para retirada"}'::jsonb)
on conflict (key) do nothing;
